### ISSUE TITLE
Blacklist of tags for page translation

### ISSUE THREAD

**Issue by Dook1** [chunibyocola/sc-translator-crx#150]
For example, to prevent translation of tags that usually contain a code block with sample programs.

**Comment by chunibyocola** [comment]
Sorry for no response. I had considered about this, but adding this will cost more computation, and very very hard to make it works "perfect". And the tag `code` is already blocked, I wonder what tags do you want to block while page translating?

**Comment by chunibyocola** [comment]
Yes, I know some websites that will wrap code with `pre` and not wrap it with `code` at the same time, like older version GitHub. But there are also some websites using `pre` to wrap text content, like Youtube video-description/comment.

I had thought about adding "Not translate content in pre element", but it is very tricky because there might be no users enabling the option due to the situation I said.

**Comment by chunibyocola** [comment]
I am accomplishing a new feature "Specify what to translate or not translate" that will be released in the next version, I think this new feature might meet your requirement.

**Comment by chunibyocola** [comment]
Version 5.5.0 has been released and is waiting for reviewing (passed on Firefox). If it isn't what you want, please just let me know, thanks.
