### ISSUE TITLE
Window position is not storing

### ISSUE THREAD

**Issue by sergeos** [chunibyocola/sc-translator-crx#34]
Dear friend,
thank you for your translator addon
but on tab with pdf document in edge the resulting window does not retain its size and position. 
the choice of settings for displaying components in this window is also reset. 
in particular, I can not remove text field with the source for translation.

**Comment by chunibyocola** [comment]
Hello,
Are you not using the build-in PDF Viewer?
If so, I will recommend that you should use the build-in PDF Viewer. Because all of the issues work well there.
If not(You are using Edge's PDF Viewer), I will recommend that you should use the Separate translate window and use the context menu(Translate the text you select) to translate text.
I might not understand these clear enough, you can upload some screenshot(s) to help with.
Thanks.
