### ISSUE TITLE
The text automatically backspace after pressing the space

### ISSUE THREAD

**Issue by ngtrian** [chunibyocola/sc-translator-crx#4]
Browser: Edge Chrome
System: Windows 10
ScTranslator version: 3.2.0

When typing slowly, the text automatically backspace after pressing the space button

![6atvEyjYo5](https://user-images.githubusercontent.com/4327817/117526800-c01c6e80-aff1-11eb-97b9-75ee27f7b693.gif)

**Comment by chunibyocola** [comment]
I will fix it next version.

And I notice that Google translate seems like unavailable in your network environment.
Google translate request the url of `translate.googleapis.com`, you can test the connectivity by pinging the url.
And you make me notice that the translate error representation need to be more specifical.

thanks for your feedback!

**Comment by ngtrian** [comment]
Google Translate after repeated use will no longer be available to me, I have also tried Retry several times, but to no 20 results. I've been waiting a long time to use Google again. 

It's the same for Bing, but it happens less often.

**Comment by chunibyocola** [comment]
Yes... It is the limit of non official.

But you can reduce the number of requests by not using `auto`.
Because `auto` will detect the source language first which request the same url as `translate`.

Maybe in the future I will rely on a language detection library, that should be helpful for the limit.
