### ISSUE TITLE
The extension is really great but I have a request related to translation by hovering with the mouse only

### ISSUE THREAD

**Issue by Rami80s** [chunibyocola/sc-translator-crx#95]
Please add the ability to translate by hovering only as a standalone option and not linked to translating the entire page As a method of translation similar to the extension called "Mouse Tooltip Translator"
https://chrome.google.com/webstore/detail/mouse-tooltip-translator/hmigninkgibhdckiaphhmbgcghochdjc

Unfortunately there is no extension for text translation through hovering in the mouse on the Firefox add-ons store and if it is available it is limited and translates words only and not text in the way that I indicated to you like "TransOver add-ons"

So i hope from you include a middle option for translation, which is to translate by hovering with the mouse only :)

Thanks

**Comment by chunibyocola** [comment]
Hello, it is a great proposal, but it is not right to do it I think.

This extension is not using the translate API provided by local translate source, it comes the cost of internet and compute of server. This feature will make a lot of requests from translation server, and most of these requests will be abandoned, because you need to make it so responsive to have a greact experience. So, it is why I think it is not right, I had thought about making a similar feature like it, but I noticed that I shouldn't do it.

So..... Sorry about that I will not add this feature into my extension.
